# service.yaml
apiVersion: v1
kind: Service
metadata:
    name: go-hello-world
spec:
    selector:
        app: go-hello-world
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
    type: LoadBalancer
